// src/components/MontarTreino/Modals/coachTechGuideData.js
// Guia de técnicas voltado pro COACH (quem está montando o treino), não pro
// aluno. Mesma lista/cores/ícones de ../../DayWorkout/techGuideData.js (pra
// manter a identidade visual), mas o texto explica como PRESCREVER a técnica
// pro aluno e quando escolhê-la -- não como executá-la em primeira pessoa
// (aquele texto é pro modo de treino do aluno, tom errado pro admin).
// Função (não objeto fixo) porque NORMAL usa cor do tema atual.

export const getCoachTechGuide = (theme) => ({
  'DROPSET': { id: 'DROPSET', title: 'DROP-SET', color: '#FF3B30', icon: 'arrow-down-bold', desc: 'COMO APLICAR:\nOriente o aluno a levar a série até a falha muscular. Assim que falhar, reduza a carga em 20 a 30% na hora e mande continuar imediatamente, sem descanso, até falhar de novo.\n\nQUANDO USAR:\nÓtimo pra intensificar o fim de um treino ou quebrar platô. Aumenta o estresse metabólico e recruta fibras que a série normal não fadigou -- indicado pra alunos mais avançados.' },
  'RESTPAUSE': { id: 'RESTPAUSE', title: 'REST-PAUSE', color: '#FF9500', icon: 'timer-sand', desc: 'COMO APLICAR:\nO aluno faz a série até a falha, descansa só 10 a 15 segundos e retoma o mesmo exercício com a MESMA carga até falhar de novo.\n\nQUANDO USAR:\nPermite acumular mais repetições totais numa carga alta em bem menos tempo que uma série tradicional. Boa opção pra treinos mais curtos ou foco em força/hipertrofia.' },
  'BISET': { id: 'BISET', title: 'BI-SET', color: theme.accent, icon: 'link-variant', desc: 'COMO APLICAR:\nMonte dois exercícios em sequência, sem descanso entre eles -- o aluno termina o primeiro e já emenda no segundo.\n\nQUANDO USAR:\nAumenta a densidade do treino e a frequência cardíaca, gerando um estresse forte no grupo trabalhado. Útil pra otimizar o tempo de academia do aluno ou intensificar uma fase do programa.' },
  'TRISET': { id: 'TRISET', title: 'TRI-SET', color: theme.accent, icon: 'link-variant', desc: 'COMO APLICAR:\nMesma lógica do bi-set, mas com três exercícios encadeados sem descanso entre eles.\n\nQUANDO USAR:\nEleva a densidade e o gasto calórico ainda mais que o bi-set, num tempo de treino bem reduzido -- boa pra fases de intensificação ou alunos com pouco tempo de academia.' },
  '21': { id: '21', title: 'MÉTODO 21', color: '#32ADE6', icon: 'numeric-7-box-multiple-outline', desc: 'COMO APLICAR:\nOriente o aluno a dividir o movimento em 3 blocos de 7 reps: 7 na metade inferior, 7 na metade superior e 7 completas -- 21 repetições no total.\n\nQUANDO USAR:\nAumenta bastante o tempo sob tensão e o fluxo sanguíneo no músculo. Boa ferramenta pra quebrar platôs em alunos que já dominam a execução básica do exercício.' },
  'CLUSTERSET': { id: 'CLUSTERSET', title: 'CLUSTER SET', color: '#BF5AF2', icon: 'chart-bar', desc: 'COMO APLICAR:\nDivida uma série pesada em blocos menores com micro-pausas -- em vez de 10 repetições diretas, o aluno faz 3, descansa 15s, faz mais 3, e assim até bater a meta.\n\nQUANDO USAR:\nPermite o aluno levantar mais carga total do que aguentaria numa série contínua, mantendo a técnica. Indicado pra foco em força e hipertrofia miofibrilar.' },
  'GVT': { id: 'GVT', title: 'GVT (10x10)', color: '#00FF7F', icon: 'numeric-10-box-multiple', desc: 'COMO APLICAR:\nPrescreva 10 séries de 10 repetições com a mesma carga (cerca de 60% da carga máxima do aluno) e 60 segundos de descanso cravado entre as séries.\n\nQUANDO USAR:\nÉ um protocolo de volume extremo -- use com moderação, em alunos já adaptados ao treino, geralmente em blocos específicos do programa, não como padrão contínuo.' },
  '1_5_REPS': { id: '1_5_REPS', title: '1 E MEIO (1.5 REPS)', color: '#FF2D55', icon: 'debug-step-over', desc: 'COMO APLICAR:\nO aluno faz o movimento completo, volta até a metade do curso, sobe de novo e só então retorna à posição inicial -- isso conta como UMA repetição.\n\nQUANDO USAR:\nAumenta o tempo sob tensão exatamente no ponto mais difícil do movimento, ajudando no ganho de massa sem precisar aumentar a carga -- boa opção pra poupar as articulações do aluno.' },
  'TUT': { id: 'TUT', title: 'T.U.T. (TEMPO SOB TENSÃO)', color: '#00C7BE', icon: 'timer-outline', desc: 'COMO APLICAR:\nDefina a cadência (segundos na descida e na subida) e cobre do aluno uma execução controlada, sem usar embalo pra levantar o peso.\n\nQUANDO USAR:\nImpede compensação por impulso e mantém o foco 100% no músculo-alvo -- bom recurso pra alunos que "roubam" no movimento ou pra fases de foco técnico.' },
  'NORMAL': { id: 'NORMAL', title: 'EXECUÇÃO PADRÃO', color: theme.textSecondary, icon: 'dumbbell', desc: 'COMO APLICAR:\nO aluno segue as séries e repetições prescritas, mantendo a postura correta.\n\nQUANDO USAR:\nÉ a base de qualquer programa -- use como padrão e reserve as técnicas avançadas acima pra pontos específicos do treino, sem exagerar na frequência.' }
});
