// src/components/DayWorkout/techGuideData.js
// Dicionário base de técnicas. Função (não objeto fixo) porque BISET e NORMAL
// usam cores do tema atual (theme.accent / theme.textSecondary).

export const getInitialTechGuide = (theme) => ({
  'DROPSET': { id: 'DROPSET', title: 'DROP-SET', color: '#FF3B30', icon: 'arrow-down-bold', audio: require('../../../assets/audio/exp_dropset.m4a'), desc: 'COMO EXECUTAR:\nFaça as repetições até a falha muscular. Imediatamente reduza a carga (cerca de 20 a 30%) e continue o exercício até falhar novamente, sem nenhum descanso.\n\nPOR QUE FAZER:\nAumenta o estresse metabólico e recruta fibras musculares mais profundas que não foram fadigadas inicialmente. Excelente para hipertrofia e "pump" máximo.' },
  'RESTPAUSE': { id: 'RESTPAUSE', title: 'REST-PAUSE', color: '#FF9500', icon: 'timer-sand', audio: require('../../../assets/audio/exp_restpause.m4a'), desc: 'COMO EXECUTAR:\nRealize a série até a falha. Descanse apenas 10 a 15 segundos e volte a fazer o exercício com a MESMA carga até falhar de novo.\n\nPOR QUE FAZER:\nPermite realizar mais repetições totais com uma carga alta (tensão mecânica extrema), gerando um forte estímulo de hipertrofia na metade do tempo.' },
  'BISET': { id: 'BISET', title: 'BI-SET', color: theme.accent, icon: 'link-variant', audio: require('../../../assets/audio/exp_biset.m4a'), desc: 'COMO EXECUTAR:\nRealize o primeiro exercício e, sem nenhum descanso, passe imediatamente para a execução do segundo exercício acoplado.\n\nPOR QUE FAZER:\nAumenta a densidade do treino, eleva a frequência cardíaca e gera um estresse absurdo na musculatura alvo, otimizando seu tempo na academia.' },
  '21': { id: '21', title: 'MÉTODO 21', color: '#32ADE6', icon: 'numeric-7-box-multiple-outline', audio: require('../../../assets/audio/exp_21.m4a'), desc: 'COMO EXECUTAR:\nDivida o movimento em 3 partes. Faça 7 repetições só na metade inferior do movimento, 7 na metade superior e 7 repetições completas. Totalizando 21 reps.\n\nPOR QUE FAZER:\nAumenta drasticamente o tempo sob tensão e o fluxo sanguíneo no local. É uma ótima ferramenta para quebrar platôs de estagnação.' },
  'CLUSTERSET': { id: 'CLUSTERSET', title: 'CLUSTER SET', color: '#BF5AF2', icon: 'chart-bar', audio: require('../../../assets/audio/exp_cluster.m4a'), desc: 'COMO EXECUTAR:\nDivida uma série pesada em pequenos blocos. (Ex: em vez de tentar 10 diretas, faça 3 reps, descanse 15s, faça mais 3 reps... até bater a meta).\n\nPOR QUE FAZER:\nPermite levantar mais carga total do que você aguentaria numa série contínua normal. Foca em força pura e hipertrofia miofibrilar sem perder a técnica.' },
  'GVT': { id: 'GVT', title: 'GVT (10x10)', color: '#00FF7F', icon: 'numeric-10-box-multiple', audio: require('../../../assets/audio/exp_gvt.m4a'), desc: 'COMO EXECUTAR:\nRealize 10 séries de 10 repetições com a mesma carga (cerca de 60% da sua força máxima) e descanso cravado de 60 segundos entre as séries.\n\nPOR QUE FAZER:\nÉ um choque brutal no corpo. O volume de treino extremo força o seu músculo a hipertrofiar para "sobreviver" ao estresse imposto.' },
  '1_5_REPS': { id: '1_5_REPS', title: '1 E MEIO (1.5 REPS)', color: '#FF2D55', icon: 'debug-step-over', desc: 'COMO EXECUTAR:\nFaça o movimento completo, volte até a metade do caminho, suba novamente e então retorne à posição inicial. Isso conta como UMA repetição.\n\nPOR QUE FAZER:\nAumenta drasticamente o tempo sob tensão no ponto de maior dificuldade do exercício, maximizando o ganho de massa sem precisar colocar cargas extremas nas articulações.' },
  'TUT': { id: 'TUT', title: 'T.U.T. (TEMPO SOB TENSÃO)', color: '#00C7BE', icon: 'timer-outline', desc: 'COMO EXECUTAR:\nExecute as repetições de forma extremamente controlada, respeitando os segundos de cadência estipulados pelo Coach tanto na fase de descida (excêntrica) quanto na de subida (concêntrica). Sem jogar o peso.\n\nPOR QUE FAZER:\nImpede o uso de "impulso" para levantar o peso. Foca 100% da força no músculo alvo, gerando hipertrofia máxima com segurança.' },
  'NORMAL': { id: 'NORMAL', title: 'EXECUÇÃO PADRÃO', color: theme.textSecondary, icon: 'dumbbell', desc: 'COMO EXECUTAR:\nSiga o número de séries e repetições estipulados, focando em manter a postura correta.\n\nPOR QUE FAZER:\nÉ a base da construção de força e hipertrofia. O foco aqui é na cadência (velocidade do movimento) e na progressão de carga treino a treino.' }
});